### ISSUE TITLE
Data connector only showing 2 pages out of 10

### ISSUE THREAD

**Issue by cclocks8** [Gladior-B-V/facebook-insights-connector#10]
Hello, I am able to successfully connect and add two facebook pages to the connector, but it doesn't see any of the others I manage. Is there something I'm missing?

![image](https://user-images.githubusercontent.com/125296411/218522180-20ec545e-2929-48b9-b96d-20c9efa55f1f.png)

**Comment by zoedufrenne** [comment]
@cclocks8 , Hi, If you don't see the other pages it could be the reason of two things,
1. Not enough rights to the accounts to connect them. or;
2. By authenticate Facebook for the Data Hub not all the acounts where selected. You have to check all the boxes when you authenticate your account. 

If you want to check this you can add a 'new' credential, but then select just the account you already connected and check the settings. You'll see which acounts are selected.

**Comment by cclocks8** [comment]
Thanks. I tried this, but when I clicked add new credential, when the facebook dialogue tries to load, it's just a blank white page.

I even tried creating a new account to see if something was wrong with mine, and it does the same thing. 

https://user-images.githubusercontent.com/125296411/220711244-e0ced09e-81eb-4c85-9335-48237b87f003.mp4

**Comment by zoedufrenne** [comment]
@cclocks8 Thanks for the video! The issue is probably in de cookies with facebook. Could you try make the connection in incognito?
