### ISSUE TITLE
Can not connect specific FB page 

### ISSUE THREAD

**Issue by tykve22** [Gladior-B-V/facebook-insights-connector#11]
I still have troubles with connecting  specific FB page with Facebook Insights connector. I do not know what is wrong. I have there only a few page to connect, if I check only two (which I need) there is: No options were provided for "Facebook Page". Check if you have the correct account/rights." I have all rights. And connection worked a few days back (and also works with others connectors). Can you please let me know, what should I Do? I tried to reconnect all, I tried to make new account at Data Hub, I tried to connect all pages, I tried to delete Data Hub from business integrations (Facebook) and add it again etc.

I have read old issues here and I have to say that, I have tried to connect one FB pages and also I have tried to connect all pages. But I am still unable to connect specific page I need to connect. And I have to repeat that connection worked two days before.

Page I need is not never on the list here (even if I check it on Facebook and give permissions )
![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/138208252/50f472fd-bdd8-4721-b4fc-27ccb28d7621). Thank you so much.

**Comment by eresfavolosx** [comment]
Greetings tykeve22,

I hope all is well! I have an issue similar to the other case posted in this project, but it does not show the pages I had connected to Gladiator previously. The accounts literally will not show up in the drop-down menu to add the account. I have tried removing the connectors from Facebook, removing all the accounts from the Gladiator Platform, removing the Business Integration from Facebook, using different Facebook accounts with admin privileges, and nothing has been working. Please let me know if there is a resolution to this issue.

**Comment by tykve22** [comment]
@favolosoboricua Hi, thank you, yes, it has to be same issue. I have added two pages, everything works, than the connection broke and than I never see that pages in the list of DataHub anymore.

**Comment by zoedufrenne** [comment]
Hi @tykve22, 
Could you try to connect your credential again? even when it's already connected, And edit your previous settings and changed it to the current profiles instead of all new profiles. (See screenshot) There has been a change in Meta (Facebook & Insta)

![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/84766152/98657898-d850-4181-b04f-6e24eb284163)

Please let me know if it worked

**Comment by Yashvardhankhemka** [comment]
Greetings @zoedufrenne, I am afraid I am still not able to see a list of all the connected pages in the Data Hub website, even after editing the settings. 

Please advise!

**Comment by zoedufrenne** [comment]
@Yashvardhankhemka can you send a screenshot of the settings in the connection screen? Are all the accounts checked?

**Comment by tykve22** [comment]
@zoedufrenne Sorry, it is still not working. I have checked all pages. 
![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/138208252/81eab816-1a68-472a-a975-be63536cd4a9), I also tried to choose only that I need. FB Pages are not listed in Data Hub :((

**Comment by Yashvardhankhemka** [comment]
Hello @zoedufrenne 

Sure, I have selected all accounts, please refer to the screenshot. 


![12312](https://github.com/Gladior-B-V/facebook-insights-connector/assets/49426119/4861813a-46f5-4e2b-b7a6-3ddd88995299)

Kindly advise how I can fix this, many thanks!

**Comment by zoedufrenne** [comment]
Hi, Could you please share your Data Hub ID? This is easily found under your profile when you click 'edit profile'. With this code I can then contact development and see if we can solve it! Like to hear from you!

**Comment by tykve22** [comment]
@zoedufrenne I tried also this:
![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/138208252/e3b75585-dbf7-4739-b1c6-a9d44b761abd)
After that I can choose from a few pages in Data Hub. But that pages I need to connect are NOT there. So, not all pages are listed in data hub. I do not know, if is it because I have them connected before (and connection works). Thank you for your advice.

**Comment by Yashvardhankhemka** [comment]
> Hi, Could you please share your Data Hub ID? This is easily found under your profile when you click 'edit profile'. With this code I can then contact development and see if we can solve it! Like to hear from you!

Hello @zoedufrenne 


Please find my Data Hub ID- google_111304181609775920961

Please let me know the next steps.

**Comment by tykve22** [comment]
@zoedufrenne Here is my ID:
Gladior Insights Connector:
ID:2128549454020769

It should be a bug.

**Comment by tykve22** [comment]
@zoedufrenne Here are my data hub account numbers:
google_103073589378308954127
google_106606955202303902200
(it does not work on both accounts)

**Comment by tykve22** [comment]
@zoedufrenne Hi, any news? Thank you so much.

**Comment by eresfavolosx** [comment]
Hi @zoedufrenne! I am also still having this issue. Thank you for all your hard work.

**Comment by zoedufrenne** [comment]
Hi, 

It may sound cumbersome, but it worked for us. 

When you create the new credentials and go back to the linked accounts in meta (the step you should have also tested before) but then reset to the new way now. 

Roadmap is as follows:  
- Reset to the old way and then save and link all the way to the Data Hub. 
- Then link the credentials again and save the account settings the new way and link all the way to the Data Hub. 

Something has changed in the connection with Meta so this is no longer working optimally. We are not getting any error messages in our code and cannot reproduce it. This way worked for us so hope it works for you too.

Please let me know!

**Comment by tykve22** [comment]
@zoedufrenne Sorry, I do not understand. What is "new way"? And what is "old way"?  Can you provide printscreens (step by step)?

**Comment by tykve22** [comment]
1) When I am creating new credentials, I am going back here:
![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/138208252/516141f4-8551-4620-8e7a-59eea39c24cc) 
2) After clicking on "edit" button I am choosing pages, I need to connect
![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/138208252/77adf9f6-8ce5-47b3-b39a-d605a539d775)

But I do not know, what is "reset to the old way" and "than link all the way to the data hub".
What is "new way" and "old way"? Thank you.

**Comment by tykve22** [comment]
@zoedufrenne Can you somehow reset (delete) data which you have for my Facebook Insights - connector on your site?. I think that Facebook still remembers old connection even if I delete connector from business integration multiple times. Sorry, but this is not about Meta, I think that there is something wrong in listing of connected pages. Other connectors (from different apps) works OK.

**Comment by zoedufrenne** [comment]
Hi @tykve22  I'll clearify:

1. Add a credential even if it's already there 
2. when you are logged in to meta, you need to click 'Edit previous settings'. 
3. You will get the following screen: 

![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/84766152/069a214a-cf52-4d85-bc84-b8b12ba696f1)

The red box, is the new option in meta. The green box is the old one. 
When you edit the setitngs you'll need to select the one that's not selected.

With the green box, you'll need to check if all the pages are there and checked. If that's the case continue to make a connection to the Data Hub. (so save the settings and click done) When you are returned to the Data Hub select your (new) credential and check if all you are accounts are there to connect. 

When it's not the case, add again the credential and edit the previous settings. Select now the other one and connect again to the Data Hub. Check then if all the accounts are there to select. 

All the accounts you'll see when you select the green box, are the accounts you can connect. If it's not there, it won't be in the Data Hub. 

Please let me know if it worked!

**Comment by tykve22** [comment]
@zoedufrenne Hi, thank you for explanation. I have tried this many times. I selected one method and then connnect it, after that I tried to connect with second method. And result is still the same. I have connected all my pages (46) via Meta, but in data hub I see only 5 of them. Can you some how reset my Facebook Insight data?  Here is my account number: google_106606955202303902200 and here is Gladior Insights Connector number 2128549454020769.

**Comment by zoedufrenne** [comment]
Hi @tykve22 There is another option, to revoke the acces of Data Hub in your Facebook account, and then connect again. To revoke acces you need to go to Facebook and go to your account settings. Go to business integrations and revoke acccess of the  Gladior Insights Connector. When you did this, then you go back to the data hub and create the credential again. 
Does this work?

**Comment by tykve22** [comment]
@zoedufrenne As I wrote before, I have tried this many times. Sorry, but something has to be done on your side, there is no option left on my side. Can you delete all information connected with Gladior Insights Connector a and my account google_106606955202303902200? But please do not delete Facebook Ads connector, which works perfectly :)
I think that there are some information still remebered (by datahub and facebook) even if I revoked acces in business integrations and also in datahub. Can you ask your development?  I am not giving it up. Thank you for your patience :)

**Comment by eresfavolosx** [comment]
Hi! I also wanted to chime in that non of these solutions are working for me either. Please let me know if any resolution is found, all of my reports have incomplete data due to this. @tykve22 @zoedufrenne

**Comment by zoedufrenne** [comment]
Hi, We've found a thread within Facebook, where as the same issue occurs. https://developers.facebook.com/support/bugs/780004130341035/?join_id=f3c1a9288f8c3 
We asked for additional premission to the endpoint they mention, when it's approved it should work. I keep you posted.

**Comment by tykve22** [comment]
Nice! Thank you :)

**Comment by eresfavolosx** [comment]
Great to hear this @zoedufrenne ! Thank you for the hard work!

**Comment by eresfavolosx** [comment]
Hi @zoedufrenne & @tykve22! I hope all is well! Have you had any luck with this? It is still not working for me on Facebook or Instagram.

**Comment by zoedufrenne** [comment]
@favolosoboricua Not yet, the review for acces can take up to 10 days. _"App Review submissions for Facebook Login and Instagram permissions are experiencing increased review times of up to 10 days."_ It's now 5 days ago that we've submitted the review. I let you know when the access is granted.

**Comment by eresfavolosx** [comment]
Got it! Thank you so much for the update!

**Comment by petrikleynhans** [comment]
Hello I'm also struggling with this. I can access 4 out of 7 pages. 
Hub ID: google_100428955155228130390

**Comment by tykve22** [comment]
@petrikleynhans 
Hi, We are waiting for Facebook. 
@zoedufrenne There are more advices in this link, did you try everything? Or are we only waiting for Facebook.
https://developers.facebook.com/support/bugs/780004130341035/?join_id=f3c1a9288f8c3
Any news?

**Comment by zoedufrenne** [comment]
Hi Everybody,

We've made some changes in the code and we've tested it and it works on our side. I want to know if it's also working from your side! 

Before it works, you have to (again) revoke the acces of Data Hub in your Facebook account, and then connect again in the Data Hub to add a new credential. To revoke acces you need to go to Facebook and go to your account settings. Go to business integrations and revoke acccess of the Gladior Insights Connector. When you did this, then you go back to the data hub and create the credential again.

Can you let me know if it worked!

**Comment by tykve22** [comment]
@zoedufrenne Thank you, sorry, nothing has change :( 
I have tried it multiple times. 
I revoked connection in Data Hub. I revoked connection in Facebook Business Integration. Then I tried to make connection again and only a few pages are at list in Data Hub. If I choose specific Pages I neeed to connect, they are not at list. So, the situation is still the same. In link you have sent (facebook) I have read something about string length, I have 46 pages I can connect, maybe is too much for api request as it is set right now. Thank you so much :)

**Comment by petrikleynhans** [comment]
Hello,
No change on my side. I've tried both "all pages" and "select Pages" options.
On my account I can see 4 out of 8 accounts. Ironically, all 4 "invisible" ones, are the ones I need access to.


Kind Regards, Petri Kleynhans 

    On Monday, July 24, 2023 at 12:12:00 PM GMT+2, tykve22 ***@***.***> wrote:  
 
 


@zoedufrenne Thank you, sorry, nothing has change :(
I have tried it multiple times.

**Comment by zoedufrenne** [comment]
Hi, Did you revoke the acces in Facebook today?  and then add the credential again even if it's already connected. You'll get new screens with extra checkboxes you have to check.  

The steps: 

You need to go to your Facebook account and click in the right corner on your profile and go to settings & privacy > settings. Then go to business integrations in the left menu and revoke acces of the **Gladior Insights Connector.**

When you've done this, go to the data hub (https://datahubapp.gladior.com/workspace) and create data source > Facebook Insights and connect again your credentials (even it's already there!).

Then you'll get a pop-up with a few checkboxes that you need to check and make the connection to the data hub.

If you followed these steps you'll be able to connect to all the accounts you have acces to.

Please let me know if it worked!

**Comment by tykve22** [comment]
Hi again, @zoedufrenne 
1) I deleted connection in business integrations as you write
2) I revoced access at data studio for Facebook Insights
3) I made new connection by clicking Add credentials (source Facebook Insights)
![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/138208252/d877b38b-8f58-4c68-b01a-5a7392814258)
4) I checked all my pages.
5) AND NOTHING has CHANGE - I see only a few pages which I can connect.

**Comment by zoedufrenne** [comment]
Did you got this screen in the process?

![image](https://github.com/Gladior-B-V/facebook-insights-connector/assets/84766152/ea66c80d-6ec7-421b-9295-43a4e3d09604)

Where the ask you to connect to all the businesses? 
And after this one you'll get to see all the pages

**Comment by tykve22** [comment]
@zoedufrenne Yes, of course, I have selected all pages and connected them. But there are not seen in Data Hub - the issue is still the same, nothing has change.

**Comment by zoedufrenne** [comment]
@tykve22 we are still waiting on a response from Facebook to our advanced permission for business_management. We changed the code and it worked in our account so we hoped it would work for you! I let you know when we have advanced permission.

**Comment by eresfavolosx** [comment]
@zoedufrenne Hi! I hope all is well and that you had a great weekend! Just to serve as one commenter on this issue, I have also tried reconnecting the pages and it did not work. Not only this, but I also coincide with @petrikleynhans that the pages which are having this issue are the ones which I need urgent access too. Thank you for all the hard you and your team does @zoedufrenne

**Comment by Hypnotoasted** [comment]
Glad to find a thread that has been my biggest problem with the Facebook Connector. It's not allowing me to connect to 1 of my pages. Even if I connect through a separate credential it has issues connecting to the exact same Facebook page.  I will be following this, thank you all for looking into this!

**Comment by eresfavolosx** [comment]
Greetings @zoedufrenne ! I hope all is well! I wanted to ask if there have been any updates with this issue? You mentioned it can take up to ten days for the request to access the other API features necessary to solve the issue. It has been 15 days since you mentioned this. Please let me know if there are any updates regarding this.

**Comment by zoedufrenne** [comment]
Hi, We are still waiting for Facebook. The request has already been submitted, however not yet approved. The request is already valid, only testing did not succeed yet. For this we immediately submitted another app review to Facebook. I hope to get feedback this week and provide a solution for you.

**Comment by eresfavolosx** [comment]
Greetings @zoedufrenne ! I hope all is well and that you had a great weekend! Thank you for the update, I hope this gets fixed very soon!

**Comment by eresfavolosx** [comment]
Greetings! I just checked my data hub account and the connections are working again! I will keep testing to make sure it works fully. Thank you for all the hard work @zoedufrenne and your team. 

Please verify @Yashvardhankhemka @tykve22 @petrikleynhans

**Comment by Hypnotoasted** [comment]
Working for me too, Thank you so much! Where can I donate?

**Comment by tykve22** [comment]
Uff, it works :)))

**Comment by zoedufrenne** [comment]
That's great to hear, thanks for checking! 
@Hypnotoasted That's really nice of you! A donation is not necessary, but is of course allowed. It is a Dutch account; Gladior B.V.;  
**IBAN**: NL 34 ABNA 0568 7305 42, **BIC**: ABNANL2A
