### ISSUE TITLE
Can't connect previosuly connected Facebook Page

### ISSUE THREAD

**Issue by eresfavolosx** [Gladior-B-V/facebook-insights-connector#12]
Greetings, 

I hope all is well! I have an issue similar to the other case posted in this project, but it does not show the pages I had connected to Gladiator previously. The accounts literally will not show up in the drop-down menu to add the account. I have tried removing the connectors from Facebook, removing all the accounts from the Gladiator Platform, removing the Business Integration from Facebook, using different Facebook accounts with admin privileges, and nothing has been working. Please let me know if there is a resolution to this issue.

**Comment by zoedufrenne** [comment]
I'll close this issue becasue of our contact in the other issue: https://github.com/Gladior-B-V/facebook-insights-connector/issues/11
