### ISSUE TITLE
Previously Connected Account not Disconnecting and not Appearing again when Trying to Add Again

### ISSUE THREAD

**Issue by eresfavolosx** [Gladior-B-V/facebook-insights-connector#13]
Greetings, 

I hope all is well and that you and your loved ones are doing great! I am again having an issue with connecting specific pages through the Facebook Insights Connector. The pages I am trying to add worked before and suddenly stopped sending any data to Google Data Studio. I have raised this issue before, but it eventually reappears, making it very difficult for my team to use this tool consistently. I have tried different methods of connecting the pages and the different profiles through the Facebook Setup tool.

Thank you in advance for your time and assistance, 

Cc. @zoedufrenne

**Comment by eresfavolosx** [comment]
Hi! Following up on this. Thank you in advance. 

@zoedufrenne

**Comment by eresfavolosx** [comment]
@zoedufrenne any updates on this? Thank you again!

**Comment by eresfavolosx** [comment]
Hi! Is there any update on this? I know this is a free tool that does an incredible job, but I will have to migrate to another tool because a reliable tool is vital for my business. Thank you for all the hard work your team does!

**Comment by zoedufrenne** [comment]
Hi @favolosoboricua I was on an holiday. Sorry for the late response. Because of the update from the side of Facebook this error occured. Did you already revoke the access and connected it again. I know that there has been an update during my holiday. The Connectors from Facebook. (Facebook Insights, Facebook Ads & Instagram). 

Please let me know!

**Comment by eresfavolosx** [comment]
Greetings @zoedufrenne, no worries, I hope you had a great holiday! I just checked if the issue was fixed, unfortunately, the issue is still not fixed on my end after reconnecting everything from scratch. 

Thank you for all the hard work,

**Comment by eresfavolosx** [comment]
Greetings @zoedufrenne, I just wanted to let you know that this issue has been fixed for me by adding a new facebook account that has access to all the same Facebook Pages. Thank you for your hard work!
