### ISSUE TITLE
Data Set Configuration Error

### ISSUE THREAD

**Issue by Lgerada** [Gladior-B-V/facebook-insights-connector#14]
Hello,

A few of my connectors are no longer working and it appears to be the same across various Facebook profiles. The data set is just not working and outputting no data. It is similar to the Instagram data error that is persistent. Is this a known issue right now? What can I do to resolve it?

It appears to be affecting page reach connector. 

Thank you.

**Comment by zoedufrenne** [comment]
Hi @Lgerada, Can you revoke data in Looker Studio and then make a new connection in the Data Hub app. please let me know if this worked. There was a big update from Meta.

**Comment by Lgerada** [comment]
I’ve tried, however on Gladiators side I’ve lost most of my existing
Instagram connectors. They are still feeding information to looker but I’ve
lost the option to select them again.

I will give it a try regardless

**Comment by Lgerada** [comment]
It's still not working, 50% of my data is there while variables such as
"Like count" are throwing data set errors.

I did revoke access and it brought back the missing connecting accounts.

**Comment by zoedufrenne** [comment]
Hi @Lgerada I went to development and we gonna check if we can fix this issue. Can you share your Data hub ID?
