### ISSUE TITLE
Community Connector Error - Error ID: 0335c06c

### ISSUE THREAD

**Issue by GildaLink** [Gladior-B-V/facebook-insights-connector#15]
Hi, I'm so happy to have found your free connectors.
My facebook insights connector was working yesterday, but now I get this error. I deleted the connector and reconnected it, but the same error appears. I'm about to show my client the report and would love this to be working if possible?

Thank You! Gilda
![Screen Shot 2023-11-23 at 10 14 35 AM](https://github.com/Gladior-B-V/facebook-insights-connector/assets/136980629/c5606da8-2f9a-44ce-bd25-d31afa721e68)

Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

Error ID: 0335c06c

**Comment by zoedufrenne** [comment]
Hi @GildaLink , nice to hear you found our connectors!
Did you also created a new credential (even if your credential was already connected)? Can you try this again? 
Please let me know if this worked. I don't get the same error messages with the facebook insights connector.

**Comment by GildaLink** [comment]
Hi, thanks for reaching out, yes i think I did, its working now 😊 on
another note, i can't get the connector to find the instgram bus account,
its just saying that there isnt one. Let me know if you have any
suggestions. And thanks so much for creating these connectors!

**Comment by zoedufrenne** [comment]
@GildaLink we have only a instagram insights account. In the Facebook Ads account you can find the Instagram ads as well! Nice to hear it's working now! thanks for letting me know.
