### ISSUE TITLE
Cannot connect to Facebook

### ISSUE THREAD

**Issue by Laxus-Diego** [Gladior-B-V/facebook-insights-connector#16]
![Capture](https://github.com/Gladior-B-V/facebook-insights-connector/assets/91722728/778c3722-ef7d-49f6-88cf-75f0b05a786c)

I cannot proceed from this step. What should I do?

**Comment by zoedufrenne** [comment]
Hi @Laxus-Diego , this is a error from Meta, I can't controll this. You can try to revoke the business acces in Facebook and try to connect again? 

Go to your personal facebook account, go to settings & privacy > settings > scroll down on the left menu and click on company intergrations > there you can delete the connection for the Gladior Insights Connector. 

Then try to create a new credential in the datahubapp.gladior.com for Facebook Insights. 
Please let me know if it worked!
