### ISSUE TITLE
Age, gender, and country city doesnt work out

### ISSUE THREAD

**Issue by davidzeng28** [Gladior-B-V/facebook-insights-connector#17]
sorry, but I don't know why the above dimension cannot work for all metrics that are provided, can you check it out, it cannot workout even on the total like based on gender, age or country

**Comment by davidzeng28** [comment]
Furthermore, which one is the post type of our post, I couldnt find one as well
Thank you very much

**Comment by zoedufrenne** [comment]
Hi @davidzeng28 , these metrics (user bound, age & gender) are depricated from Facebook Insights API. When you refresh the data fields in Looker Studio, those should disappear. There is not a data field for post type with the facebook insights api. See here the available fields: https://datahub.gladior.com/data-sources/support-facebook-insights-connector/ 

Age and gender needs to be updated, this is something that we have on the to-do list!

**Comment by davidzeng28** [comment]
Ok thank you, but may I ask why some time the page fans doesn't work as expectation on one page but other page work
Thanks

**Comment by zoedufrenne** [comment]
@davidzeng28 What kind of error do you get? When you set page fans to max. it works on our side.

**Comment by davidzeng28** [comment]
<img width="180" alt="Screen Shot 2024-02-19 at 4 59 29 PM" src="https://github.com/Gladior-B-V/facebook-insights-connector/assets/113512635/5bea98fc-d206-4be3-868d-6a14c1f6dd82">

it occured this error when i set it into max

**Comment by davidzeng28** [comment]
<img width="182" alt="Screen Shot 2024-02-19 at 5 04 32 PM" src="https://github.com/Gladior-B-V/facebook-insights-connector/assets/113512635/52867d62-197b-4496-9b42-6b23c847d316">


it occured this error when I set page fans to max, please check it out
@zoedufrenne

**Comment by davidzeng28** [comment]
> @davidzeng28 What kind of error do you get? When you set page fans to max. it works on our side.
<img width="182" alt="Screen Shot 2024-02-19 at 5 04 32 PM" src="https://github.com/Gladior-B-V/facebook-insights-connector/assets/113512635/97f0a7d5-c2f0-4e9b-913e-2c43e5b9caa6">

it occured this error when I set page fans to max, please check it out

**Comment by zoedufrenne** [comment]
Hi @davidzeng28 please click on see details, then i can see what the error is. And page fans works only as a scorecard. Not in combination in a table or another widget.

**Comment by davidzeng28** [comment]
<img width="206" alt="Screen Shot 2024-02-19 at 6 02 06 PM" src="https://github.com/Gladior-B-V/facebook-insights-connector/assets/113512635/22ccb60d-652b-429a-9e0d-895937a650ca">

it didn't allow me to use it on scorecard but available for table ~~
@zoedufrenne 
FYI: this is the error when I applied it on scorecard
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

Error ID: dbdb6e30
