### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adpesek** [Gladior-B-V/facebook-insights-connector#3]
Hello, I have problem with your connector. I tried many times in last 2 weeks use your connector, but there is still this error.

Can you help me please? :-)

Thanks

<img width="1203" alt="Snímek obrazovky 2021-05-22 v 14 45 35" src="https://user-images.githubusercontent.com/84626839/119227057-6c8b4400-bb0c-11eb-91fb-a3041bf4146e.png">

**Comment by daannijkamp** [comment]
Hi @adpesek,

For some reason I get the message: "The user has not authorized.".

Can you try to re-authorize it again maybe?
(see: https://github.com/Gladior-B-V/facebook-insights-connector/issues/1#issuecomment-776603495 )

**Comment by adpesek** [comment]
Hello, now it works. Thank you! :-)
