### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by zakadx** [Gladior-B-V/facebook-insights-connector#4]
Hi,  i can't display the Picture of post or full picture
please help thank you
![image](https://user-images.githubusercontent.com/10286443/122565735-02b17c00-d071-11eb-97d0-0bc30f673938.png)

**Comment by daannijkamp** [comment]
Hi @zakadx,

Thats weird! It should work. Are you using a sort field that you didn't specify as metric/dimension? Could you perhaps create a new data source and use our default template? Can you see the images?

**Comment by zakadx** [comment]
hi @daannijkamp 

thanks for the response, with the template still not working and i crate a new data source
https://prnt.sc/16eshuh
https://prnt.sc/16esnld

**Comment by zoedufrenne** [comment]
Hi,

We've made some adjustments to the connector and checked if the pictures are working per post. This is the case.
I will close this issue. If there is still something wrong with your dashboard, please let us know!
