### ISSUE TITLE
Cannot see all fan pages

### ISSUE THREAD

**Issue by DanielM1977** [Gladior-B-V/facebook-insights-connector#5]
Hi,
First of all thanks for the connector.
Strange thing happening.
I've connected to my facebook and on selection page i've selected all pages. When chossing a fanpage some of those pages don't show up. Is there a limit to the number of pages you can select?

**Comment by daannijkamp** [comment]
Hi @DanielM1977,

You're right. I'll try to solve this as soon as possible. 

I'll let you know when this is resolved!

Daan
(cc: @zoedufrenne)

**Comment by DanielM1977** [comment]
Thanks you so much

A quinta, 1/07/2021, 16:09, Daan Nijkamp ***@***.***>
escreveu:

**Comment by daannijkamp** [comment]
Hi @DanielM1977,

Can you maybe try again? I think I solved it. I just can't test it myself.

**Comment by pmonuth-bt** [comment]
I'm having the same problem right now
Could you support me here?

**Comment by daannijkamp** [comment]
Hi @pmonuth-bt,

I have increased the limit. It should now work again.

cc: @zoedufrenne
