### ISSUE TITLE
Error with Date on table

### ISSUE THREAD

**Issue by DanielM1977** [Gladior-B-V/facebook-insights-connector#6]
Hi
I cant seem to use date dimension on a table with message picture and other metrics. If i remove date it works fine 

![image](https://user-images.githubusercontent.com/86047963/128327139-f82b0264-ffdb-4846-998b-99f2401373c0.png)

**Comment by daannijkamp** [comment]
Hi @DanielM1977.

That's right unfortunately. "Date" field only works for graphs about the page itself, not for individual post (limitation of Facebook API). If you want to show the post date, you can probably use the "Created time" field
