### ISSUE TITLE
error in community plugin

### ISSUE THREAD

**Issue by nanskev** [Gladior-B-V/facebook-insights-connector#7]
Trying to use the FB Insights template.
Token ok, connecting okay.
First panel gets data in, the second gives an error.
![Screen Shot 2021-08-29 at 16 02 58](https://user-images.githubusercontent.com/89736846/131253362-daac9f64-e3dd-4ad9-9fe2-9de6b122edda.jpg)

any advice. Same issue with template FB Ads.

**Comment by zoedufrenne** [comment]
Hi,

We've made some adjustments to the connector and we don't get any errors anymore.
I will close this issue. If your dashboard still isn't working, please let us know!
