### ISSUE TITLE
Facebook Connector Issue

### ISSUE THREAD

**Issue by MatthewjRay** [Gladior-B-V/facebook-insights-connector#8]
I am having a connection issue with the facebook insights connector. I can get everything setup and connected for a while, but when I log back into data studio I get an unknown error that data studio cannot connect to the data source. 

I setup a new connection to the Gladiator BV application and it again worked for a short while, but eventually produced the same error message. I am wondering if it has to do with 2 factor authentication setup through a third party application. 

Let me know if this issue has been seen before and if there are any solutions. I have added a screenshot for additional context. 

<img width="571" alt="Screen Shot 2022-10-05 at 10 47 24 AM" src="https://user-images.githubusercontent.com/4120584/194093281-9782c9d0-6e14-44a0-a30a-5aac25fde550.png">

**Comment by zoedufrenne** [comment]
Hi @MatthewjRay ,

Thanks for your message.
That's not how the connector should work. I'm not really sure if the third party application disconnect the connector to the data. When we don't have access to the data this error occurs, but I will check with development. I will keep you updated!

**Comment by zoedufrenne** [comment]
Hi @MatthewjRay,

Can you test something for us? 
Can you go to datahubapp.gladior.com and check if you get an error message when you want to make a connection to this data source? 

Is it possible to send us the e-mailadres you are using for the Data Hub? We will check the error log file. You can send it to datahub-tickets@gladior.com.

**Comment by MatthewjRay** [comment]
Hey There @zoedufrenne 

I just went into datahubapp.gladior.com, and it looks like the connection was no longer showing up. I created a new connection to the same Facebook data source without any issues. I have yet to connect this data integration with datastudio.

**Comment by zoedufrenne** [comment]
Hi @MatthewjRay,

Thanks for sending us the info!
Unfortunately we can't reproduce the error. Development let me know that they made 2 weeks ago some aprovements to the connector. We hope this will fix your problem as well. 

Could you try to make a connection with Looker Studio from the Data Hub App and check if the connections stays on for longer than the short time that you've mentioned before?

I would like to hear from you!
